### ISSUE TITLE
Make it possible to build wheels for github tags

### ISSUE THREAD

**Issue by bsipocz** [astrofrog/autowheel#5]
In the astropy release procedure it was valueable to be able to build wheels before the sdist is uploaded to pypi,  so if any issues came up during wheel builds it could be still resolved for the actual release, the github tag could be reverted and redone again without needing to do a proper post release on pypi.

**Comment by pombredanne** [comment]
@bsipocz how did you solve this if I may ask?

**Comment by bsipocz** [comment]
@pombredanne - This was closed not because it got solved but part of my closember cleanup of closing some of my outdated issues. I can't recall whether it was ever done using autowheel, but here is a solution using other repos: https://github.com/astropy/astropy/blob/main/azure-pipelines.yml

**Comment by pombreda** [comment]
@bsipocz Thanks ... today I learned about closember from you :d
But I reckon you still are building your own repo with this https://github.com/OpenAstronomy/azure-pipelines-templates/blob/master/publish.yml correct?

**Comment by pombreda** [comment]
What I am really after is this:  https://github.com/pypa/cibuildwheel/discussions/1007

**Comment by bsipocz** [comment]
yes, that pipeline runs for the tags, and if the wheels are built without issues it uploads both the sdist and wheels automatically to pypi.

**Comment by bsipocz** [comment]
We haven't really done the multiple repo -- integration type of wheel building, but I don't see why you could not set it up. The only issue I see is to figure out what would trigger a build as your pipeline is usually tied to one repo (switching to github actions you may be able to get trigger events from other repos, I haven't yet tried that in practice though). But in the worst case, you could just run this all from a cron job.

That being said, I don't know about any projects that have this system set up and fully working, but please keep me posted if you find/build a solution.

**Comment by pombredanne** [comment]
> That being said, I don't know about any projects that have this system set up and fully working, but please keep me posted if you find/build a solution.

@bsipocz I sure will!
I have a home grown solution working in https://github.com/nexB/scancode-toolkit/blob/8bd896af7052d652a9de4f0f36c37f3f62f2c8eb/etc/scripts/bootstrap.py#L90  that builds wheels that I then push here https://github.com/nexB/thirdparty-packages/ ... but it uses "romp" and plain azure VMs which are not helping build the best "audited" and "delocated" wheels that cibuildwheel can build. That's why I want to switch. Ideally for me something that will use a simple requirements.txt as an input and spits back all the wheel built recursively, plain or native.
